### ISSUE TITLE
Introduce static analysis

### ISSUE THREAD

**Issue by szepeviktor** [johnbillion/query-monitor#508]
`phpstan.neon.dist`

```yaml
includes:
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
    level: max
    inferPrivatePropertyTypeFromConstructor: true
    autoload_files:
        - tests/phpstan/bootstrap.php
        - classes/QM.php
        - classes/Plugin.php
        # All other classes
        - classes/Activation.php
        - classes/Backtrace.php
        - classes/Collector.php
        - classes/Collectors.php
        - classes/debug_bar_panel.php
        - classes/debug_bar.php
        - classes/Dispatcher.php
        - classes/Dispatchers.php
        - classes/Hook.php
        - classes/Output.php
        - classes/QueryMonitor.php
        - classes/Timer.php
        - classes/Util.php
        - collectors/php_errors.php
    autoload_directories:
        - classes/
        - collectors/
        - dispatchers/
        - output/
    paths:
        - classes/
        - collectors/
        - dispatchers/
        - output/
    ignoreErrors:
        # Uses func_get_args()
        - '#^Function apply_filters(_ref_array)? invoked with [34567] parameters, 2 required\.$#'
        # TODO Define properties
        - '#^Access to an undefined property QM_#'
```

`tests/phpstan/bootstrap.php`

```php
Oh! I've deletes the query-monitor directory without copying this file here!
It contained
- core constants not listed in phpstan-wordpress
- some 3rd-party functions stubs
- QM constants
```

```
composer require --dev szepeviktor/phpstan-wordpress
vendor/bin/phpstan analyze -l 2
```

Then raise level!
